### ISSUE TITLE
imcsdk cannot log in to a 3.0(3a) system

### ISSUE THREAD

**Issue by andywis** [CiscoUcs/imcsdk#133]
Hi.
We've upgraded our firmware to 3.0(3a) to take advantage of new features, but now cannot connect to the CIMC using the IMCSDK library.

I've noticed that the documentation here: http://imcsdk.readthedocs.io/en/latest/history.html says it supports 3.0(1c). Do you have a plan for supporting 3.0(3a)? How can I help fix this?

I'm calling handle.login() and I get the following response immediately.
My code essentially does this:
```
49        self.handle = ImcHandle(hostname, username, password)
50        self.handle.login()
```
and here's the traceback...

Here's the traceback:
```
Traceback (most recent call last):
  File "./my_code.py", line 50, in __init__
    self.handle.login()
  File "/usr/local/lib/python2.7/dist-packages/imcsdk/imchandle.py", line 94, in login
    return self._login(auto_refresh, force, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/imcsdk/imcsession.py", line 571, in _login
    response = self.post_elem(elem, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/imcsdk/imcsession.py", line 275, in post_elem
    response_str = self.post_xml(xml_str, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/imcsdk/imcsession.py", line 226, in post_xml
    response_str = self.post(uri=imc_uri, data=xml_str, read=read, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/imcsdk/imcsession.py", line 206, in post
    response = self.__driver.post(uri=uri, data=data, read=read, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/imcsdk/imcdriver.py", line 264, in post
    response = opener.open(request, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/imcsdk/imcdriver.py", line 95, in https_open
    return self.do_open(TLSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 104] Connection reset by peer>
```

My system:
$ uname -a
Linux myserver 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ python --version
Python 2.7.6
$ pip freeze | grep imc
imcsdk==0.9.2.0

**Comment by andywis** [comment]
Further investigation suggests this is a TLS connection problem, where the TLSHandler in imcdriver.py is enforcing TLSv1, but it should be allowing any TLS version.

I was able to work around this by monkeypatching TLSHandler.https_open() to use an HTTPSConnection object instead of a TLSConnection object.
here: https://github.com/CiscoUcs/imcsdk/blob/master/imcsdk/imcdriver.py#L95

My Monkeypatch looks like this:
```
from imcsdk.imcdriver import TLSHandler
def mp_tlshandler_https_open(self, req):
    from httplib import HTTPSConnection
    return self.do_open(HTTPSConnection, req)
TLSHandler.https_open = mp_tlshandler_https_open
```

My monkey patch works against the following firmware versions:
  2.0(10b)
  2.0(13i)
  3.0(3a)
  
Please let me know if there's anything I can do to help

**Comment by britthouser** [comment]
Andy - Can you also try with python 2.7.9?

**Comment by andywis** [comment]
Hi Britt.
It works fine in 2.7.9. (no traceback)

**Comment by log1-c** [comment]
Hi @andywis,

can you assist me with where I have to put the lines of code from your Monkeypatch?
I have the same/a similar problem that I can't use the IMC Nagios monitoring plugin because it runs for ever without finishing.
I hope that your patch maybe works around the issue.

> sudo -u nagios ./cisco_imc_nagios -H 10.10.250.41 -u monitoring -p password -q ComputeRackUnit -t class --NoSsl
> ^C
> Traceback (most recent call last):
>   File "./cisco_imc_nagios", line 864, in <module>
>     dump_xml=args_obj.debug)
>   File "/usr/local/lib/python2.7/dist-packages/ImcSdk/ImcHandle.py", line 394, in login
>     response = self.aaa_login(username, password, dump_xml)
>   File "/usr/local/lib/python2.7/dist-packages/ImcSdk/ImcHandle.py", line 959, in aaa_login
>     response = self.xml_query(method, WriteXmlOption.DIRTY, dump_xml)
>   File "/usr/local/lib/python2.7/dist-packages/ImcSdk/ImcHandle.py", line 208, in xml_query
>     resp = opener.open(req)
>   File "/usr/lib/python2.7/urllib2.py", line 429, in open
>     response = self._open(req, data)
>   File "/usr/lib/python2.7/urllib2.py", line 447, in _open
>     '_open', req)
>   File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
>     result = func(*args)
>   File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
>     return self.do_open(httplib.HTTPConnection, req)
>   File "/usr/lib/python2.7/urllib2.py", line 1201, in do_open
>     r = h.getresponse(buffering=True)
>   File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
>     response.begin()
>   File "/usr/lib/python2.7/httplib.py", line 453, in begin
>     version, status, reason = self._read_status()
>   File "/usr/lib/python2.7/httplib.py", line 409, in _read_status
>     line = self.fp.readline(_MAXLINE + 1)
>   File "/usr/lib/python2.7/socket.py", line 480, in readline
>     data = self._sock.recv(self._rbufsize)

>python --version
>Python 2.7.12

> pip freeze | grep imc
> imcsdk==0.9.3.0

**Comment by andywis** [comment]
Hi @log1-c -- the monkeypatch is to go in your code that makes use of the imcsdk. 
In my situation, the patch was only needed with python 2.7.6 and earlier.

Hope you can fix your problem.
Andy

**Comment by log1-c** [comment]
Thanks for the quick reply! Will try it out
