### ISSUE TITLE
Value starting letter should be Uppercase

### ISSUE THREAD

**Issue by sandss** [CiscoUcs/imcsdk#155]
https://github.com/CiscoUcs/imcsdk/blob/8cb4439e0bd036dcd5c71caf145f58e7b1cb9e68/imcsdk/apis/server/boot.py#L208

When trying to call boot_order_precision_set from imcsdk.apis.server.boot recieve an error:

> [ErrorCode]: ERR-xml-parse-error[ErrorDescription]: XML PARSING ERROR: Element 'lsbootVMedia', attribute 'state': [facet 'enumeration'] The value 'enabled' is not an element of the set {'Disabled', 'Enabled'}. Element 'lsbootVMedia', attribute 'state': 'enabled' is not a valid value of the local atomic type.

**Comment by vvb** [comment]
fixed now
