### ISSUE TITLE
backup_imc without 'passphrase' parameter does not throw exception

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/imcsdk#16]
When try to run backup_imc without 'passphrase' parameter, the script comes out without throwing any exception.
For IMC firmware 2.0(1a) and above, 'passphrase' is a mandatory parameter and hence it should throw an exception.

**Comment by waghswapnil** [comment]
will be fixed by #19

**Comment by waghswapnil** [comment]
fixed by #19

**Comment by waghswapnil** [comment]
fixed by #22
