### ISSUE TITLE
auto_refresh leads to random authorization required errors

### ISSUE THREAD

**Issue by mtimm** [CiscoUcs/imcsdk#162]
I recently attempted to add auto_refresh to imcsdk sessions and when doing so I started to see random "Authorization required" errors.

It appears that there is no locking or other concurrency protection on the cookie so it is possible for the auto refresh to take place, refresh the cookie but other consumers of the cookie may not have the updated one resulting in authorization required errors.

Seems like there needs to be some locking mechanism on the cookie so when auto_refresh starts it can lock the cookie and prevent others from using it until the auto refresh is complete or conversely if the main thread for the session is in the middle of a transaction the auto refresh has to wait for the transaction to be complete before it can do the refresh.

**Comment by mtimm** [comment]
Implementing locks seems to kill performance tremendously.  What used to take 20 minutes to run against 36 servers is now taking over an hour.  It may be better for clients to do the refresh on their own at strategic times.

**Comment by vvb** [comment]
Hi @mtimm,

so I have noticed the `Authorization required` error once in a while. I haven't given this the time it deserves. I will try writing a script that does a login and keeps refreshing. Will run this over-night and see if I can reproduce this. Using locks is probably a bad idea here. I will post an update as I see some results.

**Comment by mtimm** [comment]
@vvb I can easily recreate this using the automation we have in the Tetration BU to configure nodes before we reimage them.  This automation does many things but the basic breakdown is:

1. Set boot order precise to be uefishell, hdd, pxe, vmedia in case the node reboots mid-configuration it will end up in uefishell instead of trying to pxe boot (because there is no hdd bootable media).  This allows us to recover and configure the node in nearly 100% of the cases.
2. Get bios settings.
3. Set bios settings to default.
4. unmount al vmedia
5. Set power restore policy.
6. Set platform characterization.
7. Set fan policy.
8. Set CIMC mgmt interface parameters.
9. Get the memory (DIMM) info and verify no dimms are inoperable.
10. Wait for the host to be powered on (99.9% of the time it already is).
11. Configure VIC's - we have two installed in all our systems.
12. Get the current storage policy.
13. Set the pcie option rom.
14. Clear any pinned cache on the controller.
15. Clear any foreign config on the controller.
16. Get the physical drive info and verify no faults exist on the drives.
17. Delete all vd's and reset the pd's then ensure the drives are in unconfigured good state.
18. Create the vd's, for the most part we do raid 0 so one pd == one vd.  Our automation does do other forms of raid and we do raid 1 as well.
19. Set the cache policies for the drives.
20. Update the boot order precise to boot hdd, pxe, vmedia.
21. Wait for all other nodes (we do them in groups of 36 is separate threads so they go in parallel) to complete step 20, then reboot them all.

After step 21 they install the os from a pxe server.  As you can probably imagine this whole process can take 15 - 20 minutes unless a node reboots and has to then come back up to the uefishell so it can continue with the configuration on that node in which case it can take close to 30 minutes.  This is longer than the session timeout so auto refresh tends to kick in and without any locking it's entirely possible to have the refresh transaction in flight and some other transaction start before the cookie has been updated.
