### ISSUE TITLE
Python3: apis.server.storage.virtual_drive_create TypeError with raid_level=1

### ISSUE THREAD

**Issue by dsoper2** [CiscoUcs/imcsdk#172]
Following command is working with python 2.7 by returning TypeError with Python 3.6: Storage.virtual_drive_create(handle=handle,drive_group=[[1,2]],raid_level=1,controller_type="SAS",controller_slot="MRAID")
TypeError: unsupported operand type(s) for >>: 'float' and 'int'
It works if I leave the raid_level blank or set to 0

**Comment by tfchan0** [comment]
Have the same issue, just wonder if any update on this?   Thanks.
