### ISSUE TITLE
backup_imc with protocol="none" throws an exception

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/imcsdk#18]
When trying backup_imc with protocol="none", the script throws following error - 

_[ErrorCode]: ERR-xml-parse-error[ErrorDescription]: XML PARSING ERROR: Element 'mgmtBackup', attribute 'proto': [facet 'enumeration'] The value 'none' is not an element of the set {'ftp', 'tftp', 'sftp', 'scp', 'http'}. Element 'mgmtBackup', attribute 'proto': 'none' is not a valid value of the local atomic type._

Checked with IMC firmware 2.0(8d) and 2.0(9e)

**Comment by waghswapnil** [comment]
`proto = "none"` is a value returned in the response and not a valid value for the request.

**Comment by waghswapnil** [comment]
Will not be addressing this issue as the backend specifies the appropriate list of values
