### ISSUE TITLE
boot_order_precision_get shows stale info after boot_order_precision_set success

### ISSUE THREAD

**Issue by rl344** [CiscoUcs/imcsdk#181]
How to reproduce error:

1) run get boot order script ( below ) 
2) run set boot order script (below,  and confirm correct by viewing cimc web UI ) 
3) run get boot order script ( below ) 

Problem: Step 3 shows same info as Step 1
However, I know that setting boot order from below script works b/c I can confirm via the cimc web UI.

Question: Is the boot order cached somewhere ?  Why does the script show stale info ?

```
# get boot order
import argparse
from imcsdk.imchandle import ImcHandle
from imcsdk import *

h = ImcHandle(args.host,args.username,args.password)
h.login()
boot_order = boot_order_precision_get(h,dump=False)
print boot_order
h.logout()
```

```
# set boot order
import argparse
from imcsdk.imchandle import ImcHandle
from imcsdk import *
from imcsdk.mometa.lsboot import LsbootDevPrecision


h = ImcHandle(args.host,args.username,args.password)
h.login()
boot_devices = [
       [
            {"order": "1", "device-type": "pxe", "name": "testpxe1"},
            {"order": "2", "device-type": "hdd", "name": "testhdd2"},
        ],
    ]

boot_order_precision_set(h, boot_devices=boot_devices[0])
h.logout()


```

**Comment by waghswapnil** [comment]
@rl344 : The Set api sets the configured boot order. The get api returns the actual boot order. The difference is that you could have setup a device in the boot order that is actually not present. In such cases, the actual boot order will skip such devices.

**Comment by rl344** [comment]
The above code uses devices that are already present and enabled in the Advanced section of the cimc web ui.
My Set code only changes order and name.  Set changes are confirmed via cimc web ui.
