### ISSUE TITLE
ULTM hardware type not supported. 

### ISSUE THREAD

**Issue by apozass** [CiscoUcs/imcsdk#195]
Hello Team, 

I've found that the UCS model ULTM-Cxxx is not supported, I've checked the code and as stated in the post https://github.com/CiscoUcs/imcsdk/issues/130  

In function "_validate_model" of imcsession.py:

`valid_model_prefixes = ["UCSC", "UCS-E", "UCSS", "HX"]`

should be

`valid_model_prefixes = ["UCSC", "UCS-E", "UCSS", "HX", "ULTM"]`
 

**- Console logs and stack trace, if any.**

PYTHON testing:
```
>>> from imcsdk.imchandle import ImcHandle
>>> handle=ImcHandle("1.1.1.1","USER","PSWD")
>>> handle.login()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/opt/anaconda3/envs/py2/lib/python2.7/site-packages/imcsdk/imchandle.py", line 143, in login
    return self._login(auto_refresh=auto_refresh, force=force, timeout=timeout)
  File "/Users/user/opt/anaconda3/envs/py2/lib/python2.7/site-packages/imcsdk/imcsession.py", line 589, in _login
    raise ImcLoginError("Not a supported server.")
imcsdk.imcexception.ImcLoginError: Not a supported server.
```
IMCSDK version in use 

```
Name: imcsdk
**Version: 0.9.7**
Summary: python SDK for Cisco UCS IMC
Home-page: https://github.com/ciscoucs/imcsdk
Author: Cisco Systems
Author-email: ucs-python@cisco.com
License: http://www.apache.org/licenses/LICENSE-2.0
```

- Your operating system name and version.

macOS Catalina 

- Any details about your local setup that might be helpful in troubleshooting.

Using Anaconda environment with python 2.7

```
$ python -V
Python 2.7.17 :: Anaconda, Inc.
```
- Detailed steps to reproduce the bug.

Try to run login() method to a UCS model **ULTM-C220-M5SX-CM** 
```
HOSTNAME /chassis # show detail 
Chassis:
    Power: on
    Serial Number: <SERIAL>
    Product Name: 
    PID : ULTM-C220-M5SX-CM
    UUID: 
    Locator LED: on
    Description: 
    Asset Tag: Unknown
```

I've changed the Prefix list in valid_model_prefixes and was able to successfully run the login() method.

LOGS
[UTLM_IMSDK_LOGS.log](https://github.com/CiscoUcs/imcsdk/files/3875923/UTLM_IMSDK_LOGS.log)

**Comment by mseashor** [comment]
Can confirm.  I am also seeing this issue - above codefix appears to work.

**Comment by akripo** [comment]
Hello 
The same applies for the model BE6M-M5-K9 we got recently . After applying the following change seems to work:
```
[haris@harissdesk imcsdk]# diff  /modified/imcsession.py /original/imcsession.py
475c475
<         valid_model_prefixes = ["UCSC", "UCS-E", "UCSS", "HX", "BE6M"]
---
>         valid_model_prefixes = ["UCSC", "UCS-E", "UCSS", "HX"]
```

**Comment by mseashor** [comment]
This issue still persists.  I’m glad to see some activity in the repo!

I can update PR #196 with the change from @makripodis if this is desired (and/or rebase as PR has a conflict).  Or we can close with “won’t fix” (I can imagine keeping up to date with different UCS PIDs may not be the desired way to fix this) or something else the dev team suggests, but IMO it’s not stale.

**Comment by vvb** [comment]
@mseashor - Please go ahead and update the PR with the changes. We can merge.
