### ISSUE TITLE
Observation: Upload Certificate terminates the xmlapi session, hence the script throws the error while logging out of imc

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/imcsdk#20]
Execute the following to upload certificate - 

_upload_cert = UploadCertificate(parent_mo_or_dn="sys/cert-mgmt",
                                            admin_action='remote-cert-upload',
                                            user=username,
                                            pwd=password,
                                            protocol='scp',
                                            remote_server=ip,
                                            remote_file='/path/to/file.crt'
                                            )
  handle.add_mo(upload_cert,modify_present=True)_

Since this activity terminates the xml-api connection in the background, if the user tries to logout after this, the script throws the error.

To avoid the error, create a login handle with auto_refresh=True

**Comment by waghswapnil** [comment]
Will be addressed by #49 . 
Connection termination is expected. If auto_refresh is done, connection will be re-established.
