### ISSUE TITLE
Default values of cimc_secure_boot, stop_on_error, verify_update and timeout=None incorrect in function "update_imc_firmware_huu". 

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/imcsdk#21]
Execute the following code for firmware update - 

_update_imc_firmware_huu(handle=handle,
                                          remote_ip=ip,
                                          remote_share='nfs/sharepath/filename.iso',
                                          share_type='nfs',
                                          username=username,
                                          password=password,
                                          update_component='all')_

The script throws 'invalid value exception' for _stop_on_error, verify_update,_ _cimc_secure_boot_ and _timeout_ parameter which should not be passed as 'None' by default.

**Comment by waghswapnil** [comment]
fixed by #25
