### ISSUE TITLE
failed to remove Managed object for classId 'LsbootVirtualMedia' using function remove_imc_managedobject

### ISSUE THREAD

**Issue by ghost** [CiscoUcs/imcsdk#3]
Using ImcSdk 0.7.2
when function remove_imc_managedobject() called with input either in_mo or class_id and params={"Dn": "'sys/rack-unit-1/boot-policy/vm-read-only'", "Access": 'read-only'}
It fails to remove with error:
ImcException: [ErrorCode]: ERR-xml-parse-error [ErrorDescription]: XML PARSING ERROR: Element 'lsbootVirtualMedia': The attribute 'access' is required but missing.

The function  remove_imc_managedobject takes only 2 attributes 'Dn' as 'Key' and 'class_id'

please do needful and make available the updated version.

**Comment by vvb** [comment]
@mukhtar13 can you raise this in https://github.com/CiscoUcs/ImcSdk_legacy
older imcsdk repo has been moved there. 

New SDK provides a different way of doing the same.
