### ISSUE TITLE
backup_imc without 'entity' param on modular server throws error. 'Entity' param should be mandatory.

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/imcsdk#50]
Python version: 2.7.12
IMC models: classic / modular
Firmware: 2.0(13e)

**Description:**
When running **_backup_imc_** without **_'entity'_** param on modular server, the script throws following error - 
_ERR-xml-parse-error[ErrorDescription]: XML PARSING ERROR: Element 'mgmtBackup': The attribute 'entity' is required but missing._

**Expected:**
The 'entity' param should be made mandatory so that it works both with classic and modular.

**Comment by tanmayx** [comment]
Checked with the latest code, on both classic/modular servers, with and without 'entity' param is working fine. We can close this bug.

**Comment by waghswapnil** [comment]
will be addressed by #49

**Comment by waghswapnil** [comment]
fixed by #49
