### ISSUE TITLE
Running tech support creates extra file with '.done' extension

### ISSUE THREAD

**Issue by tanmayx** [CiscoUcs/imcsdk#51]
Python version: 2.7.12
IMC models: classic/modular
IMC firmware: 2.0(13e)

**Description**:
After running the following code, the tech support file gets generated but also an extra file with '.done' extension gets created -

_get_imc_tech_support(handle=handle, remote_host=remote_host_ip, remote_file='/remote_path/filename.tar.gz', protocol='scp', username=username,                     password=password, component='all')_

**Observation**:
apart from **filename.tar.gz**, extra file **'filename.tar.gz.done'** also gets created.

**Expected**:
Only **'filename.tar.gz'** should be created.

**Comment by vvb** [comment]
@tanmayx is this specific to triggering tech support via SDK? What is the behaviour when you take tech support using the UI ? I am fairly certain you would notice the same. this is probably something for the IMC backend team to take care of.

**Comment by tanmayx** [comment]
@vvb, yes this was triggered via sdk. Will check it via UI and update you.

**Comment by waghswapnil** [comment]
I see the same behaviour when triggered via UI. Checking with the backend team.

**Comment by vvb** [comment]
not saying that this file should exist. But I am not sure how this affects anything, it is generally not even exposed to the user unless someone loads a debug plugin and looks around in the file system.. right? Not sure, if we should care right now.

**Comment by waghswapnil** [comment]
@vvb This gets created in the remote location where tech-supported gets eventually downloaded.

**Comment by tanmayx** [comment]
@vvb, I tried from UI and the extra file gets created as well.
